const plugin = require('tailwindcss/plugin');

module.exports = {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  corePlugins: {
    preflight: false, // 關閉全域樣式(@base)，避免和其他組件庫衝突
  },
  darkMode: 'class',
  plugins: [
    plugin(({ addVariant, e }) => {
      addVariant('child(3n)', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => `.${e(`child(3n)${separator}${className}`)}:nth-child(3n)`);
      });
      addVariant('child(2)', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => `.${e(`child(2)${separator}${className}`)}:nth-child(2)`);
      });
    }),
  ],
  theme: {
    extend: {
      backgroundColor: {
        layout: 'var(--layout-bg)',
        // home: 'var(--home-bg)',
        header: 'var(--header-bg)',
        sidebar: 'var(--sidebar-bg)',
        'btn-load-more': 'var(--load-more-btn-bg)',
        'sidebar-default-avatar': 'var(--sidebar-default-avatar-bg)',
        'mobile-sidebar-top': 'var(--mobile-sidebar-top-bg)',
        'sidebar-balance': 'var(--sidebar-balance-bg)',
        'dropdown-balance': 'var(--dropdown-balance-bg)',
        'pc-sidebar-selected': 'var(--pc-sidebar-selected-bg)',
        dropdown: 'var(--dropdown-bg)',
        modal: 'var(--modal-bg)',
        component: 'var(--component-bg)',
        'second-component': 'var(--component-second-bg)',
        'notice-timer': 'var(--notice-timer-bg)',
        'notice-icon': 'var(--notice-icon-bg)',
        'notice-bg': 'var(--notice-bg)',
        'btn-primary': 'var(--primary-btn-bg)',
        'btn-primary-hover': 'var(--primary-btn-bg-hover)',
        'btn-second': 'var(--second-btn-bg)',
        'btn-second-hover': 'var(--second-btn-bg-hover)',
        'btn-disable': 'var(--disable-btn-bg)',
        'amount-btn': 'var(--amount-btn-bg)',
        'amount-btn-active': 'var(--amount-btn-active)',
        'input-default': 'var(--default-input-bg)',
        'input-active': 'var(--active-input-bg)',
        'input-disable': 'var(--disable-input-bg)',
        'game-menu': 'var(--game-menu-bg)',
        'category-menu': 'var(--category-menu-bg)',
        'category-menu-item-c-active': 'var(--active-category-menu-item-c-bg)',
        'category-menu-item-d-active': 'var(--active-category-menu-item-d-bg)',
        'scroll-track': 'var(--scroll-track)',
        'scroll-thumb': 'var(--scroll-thumb)',
        mask: 'var(--mask-bg)',
        footer: 'var(--footer-bg)',
        'inner-footer': 'var(--inner-footer-bg)',
        marquee: 'var(--marquee-bg)',
        'row-even': 'var(--row-even-bg)',
        'row-odd': 'var(--row-odd-bg)',
        pagination: 'var(--pagination-bg)',
        'pagination-page': 'var(--pagination-page-bg)',
        'pagination-page-hover': 'var(--pagination-page-bg-hover)',
        'pagination-page-active': 'var(--pagination-page-bg-active)',
        'layout-bd': 'var(--border-color)',
        'select-card': 'var(--select-card-bg)',
        'select-card-modal-hover': 'var(--select-card-modal-bg-hover)',
        tag: 'var(--tag-bg)',
        'tag-hover': 'var(--tag-bg-hover)',
        'tag-active': 'var(--tag-bg-active)',
        'game-inner': 'var(--game-inner-bg)',
        'game-lobby-filter': 'var(--game-lobby-filter-bg)',
        step: 'var(--step-bg)',
        notify: '#ff4343',
        date: 'var(--date-bg)',
        'mobile-header': 'var(--mobile-header-bg)',
        'warn-info': 'var(--warn-info-bg)',
        'game-card': 'var(--game-card-bg)',
        'online-service-btn': 'var(--online-service-btn-bg)',
        'online-service-btn-hover': 'var(--online-service-btn-bg-hover)',
        'slider-rail': 'var(--slider-rail-bg)',
        'sport-info': 'var(--sport-home-info-bg)',
        'deposit-teach': 'var(--deposit-teach-bg)',
        'more-match-info': 'var(--more-match-info-bg)',
        'bet-option-active': 'var(--bet-option-active-bg)',
        'bet-option': 'var(--bet-option-bg)',
        'sidebar-balance-refresh': 'var(--sidebar-balance-refresh-bg)',
        'vip-swiper': 'var(--vip-swiper-bg)',
        about: 'var(--about-bg)',
        'header-dropdown': 'var(--header-dropdown-bg)',
        'pc-deposit-teach': 'var(--pc-deposit-teach-bg)',
        'pc-deposit-teach-hover': 'var(--pc-deposit-teach-hover)',
        'profile-balance': 'var(--profile-balance-bg)',
        'search-header': 'var(--search-header-bg)',
        'header-dropdown-second': 'var(--header-dropdown-second-bg)',
        'login-user': 'var(--login-user-bg)',
        'no-data-btn': 'var(--no-data-btn-bg)',
        'vip-progress': 'var(--vip-progress-bg)',
        'vip-deposit': 'var(--vip-deposit-bg)',
        'vip-bet': 'var(--vip-bet-bg)',
        'sport-game-category': 'var(--mobile-game-category-bg)',
        'collapse-active': 'var(--collapse-active-bg)',
        'rebate-btn': 'var(--rebate-btn-bg)',
        'rebate-tip': 'var(--rebate-tip-bg)',
        'play-game-btn': 'var(--play-game-btn-bg)',
        'play-game-btn-hover': 'var(--play-game-btn-hover-bg)',
        'share-top': 'var(--share-top-bg)',
        'tabs-top': 'var(--tabs-top-bg)',
        'vip-swiper-top': 'var(--vip-swiper-top-bg)',
        'vip-swiper-even': 'var(--vip-swiper-even-bg)',
        'more-btn': 'var(--more-btn-bg)',
        'vip-swiper-level': 'var(--vip-swiper-level-bg)',
        'rebate-table-hover': 'var(--rebate-table-hover-bg)',
        'pc-profile-game': 'var(--pc-profile-game-bg)',
        'pc-profile-option': 'var(--pc-profile-option-bg)',
        'profile-vip-top': 'var(--profile-vip-top-bg)',
        'profile-info-hover': 'var(--profile-info-hover)',
        league: 'var(--league-bg)',
        'pc-sidebar-tooltip': 'var(--pc-sidebar-tooltip-bg)',
        'game-item': 'var(--game-item-bg)',
        'pc-about': 'var(--pc-about-bg)',
        'about-info': 'var(--about-info-bg)',
        'pc-about-info': 'var(--pc-about-info-bg)',
        'vip-faq-hover': 'var(--vip-faq-hover)',
        'deposit-teach-layout': 'var(--deposit-teach-layout-bg)',
        'detail-index': 'var(--detail-index-bg)',
        'wallet-index': 'var(--wallet-index-bg)',
        'exchange-btn': 'var(--exchange-btn-bg)',
        'demo-btn': 'var(--demo-btn-bg)',
        'demo-btn-hover': 'var(--demo-btn-bg-hover)',
        'pc-exchange-btn': 'var(--pc-exchange-btn-bg)',
        download: 'var(--download-bg)',
        'kyc-platform': 'var(--kyc-platform-bg)',
        'transition-info': 'var(--transition-info-bg)',
        'game-mask': 'var(--game-mask-bg)',
        'sms-disable-btn': 'var(--sms-disable-btn-bg)',
        'info-with-tag': 'var(--info-bg-with-tag)',
        'platform-switch': 'var(--platform-switch-bg)',
        'game-category-active': 'var(--game-category-active-bg)',
        'sport-amount-num-btn': 'var(--sport-amount-num-btn-bg)',
        'sport-amount-fast-btn': 'var(--sport-amount-fast-btn-bg)',
        'sport-b-collapse': 'var(--sport-b-collapse-bg)',
        'sport-b-collapse-origin': 'var(--sport-b-collapse-origin-bg)',
        'sport-b-collapse-bet': 'var(--sport-b-collapse-bet-bg)',
        'sport-b-bet-option': 'var(--sport-b-bet-option-bg)',
        switch: 'var(--switch-bg)',
        'invite-desc-card': 'var(--share-desc-card-bg)',
        'invite-reward-bg': 'var(--share-reward-bg)',
        'invite-reward-list': 'var(--share-reward-list)',
        'invite-reward-first': 'var(--share-reward-first)',
        'invite-reward-second': 'var(--share-reward-second)',
        'invite-reward-third': 'var(--share-reward-third)',
        'invite-reward-top': 'var(--share-reward-top)',
        'betting-slip-ticket': 'var(--betting-slip-ticket-bg)',
        'login-btn': 'var(--login-btn-bg)',
        'swiper-pagination-bullet': 'var(--swiper-pagination-bullet-bg)',
      },
      backgroundImage: {
        'slider-track': 'var(--slider-track-bg)',
        'sport-type': 'var(--sport-type-bg)',
        'live-game': 'var(--live-game-bg)',
        app: 'var(--app-bg)',
        'app-gradient': 'var(--app-bg-gradient)',
        'invite-leaderboard': 'var(--share-leaderboard-bg)',
        'btn-primary': 'var(--primary-btn-bg)',
        'btn-primary-hover': 'var(--primary-btn-bg-hover)',
        'header-btn-bg': 'var(--header-btn-bg)',
        'header-btn-bg-hover': 'var(--header-btn-bg-hover)',
        'mobile-e-category-btn': 'var(--mobile-e-category-btn-bg)',
        'mobile-e-category-btn-active': 'var(--mobile-e-category-btn-active-bg)',
      },
      colors: {
        layout: 'var(--layout-bg)',
        'clear-cache': 'var(--clear-cache-border-color)',
        'more-match-info-tx': 'var(--more-match-info-text-color)',
        'sport-info': 'var(--sport-home-info-bg)',
        'online-service-hint': 'var(--online-service-hint-btn-bg)',
        'layout-tx': 'var(--font-color)',
        'second-layout-tx': 'var(--second-font-color)',
        'color-layout': 'var(--layout-bg)',
        'layout-bd': 'var(--border-color)',
        'tabs-top': 'var(--tabs-top-bg)',
        'btn-primary': 'var(--primary-btn-color)',
        'btn-second': 'var(--second-btn-color)',
        'btn-second-active': 'var(--second-btn-active-color)',
        'btn-disable': 'var(--disable-btn-color)',
        'btn-load-more-tx': 'var(--load-more-btn-color)',
        'btn-load-more-hover-tx': 'var(--load-more-btn-color-hover)',
        'amount-btn-hover-bd': 'var(--amount-btn-border-hover)',
        'input-default-bd': 'var(--default-input-border)',
        'input-default-tx': 'var(--default-input-color)',
        'input-active-bd': 'var(--active-input-border)',
        'input-hover-bd': 'var(--hover-input-border)',
        'input-active-tx': 'var(--active-input-color)',
        'input-disable-tx': 'var(--disable-input-color)',
        'input-disable-bd': 'var(--disable-input-bg)',
        'input-placeholder': 'var(--input-placeholder)',
        'dropdown-hover': 'var(--dropdown-bg-hover)',
        'dropdown-tx-active': 'var(--dropdown-tx-active)',
        'second-info': 'var(--second-info-bg)',
        active: 'var(--active-color)',
        addition: 'var(--addition-color)',
        modal: 'var(--modal-border)',
        notice: 'var(--notice-border)',
        link: '#2699fb',
        higher: '#38C522',
        lower: '#ff4343',
        gray: '#bbb',
        'dropdown-search-bd': 'var(--dropdown-search-border-color)',
        'step-num': 'var(--step-num)',
        step: 'var(--step-text)',
        'promotion-card': 'var(--promotion-card-bg)',
        'promotion-desc': 'var(--promotion-desc-color)',
        'promotion-base': 'var(--promotion-base-color)',
        'select-card-hover-bd': 'var(--select-card-hover-bd)', // 可刪除
        'warn-info': 'var(--warn-info)',
        'warn-info-bd': 'var(--warn-info-bd)',
        column: 'var(--column-text)',
        'game-card': 'var(--game-card-bd)',
        'promotion-gold': 'var(--promotion-gold-color)',
        // 'deposit-btn-border': 'var(--go-deposit-btn-border-color)',
        'level-1': 'var(--level-one-color)',
        'level-2': 'var(--level-two-color)',
        'level-3': 'var(--level-three-color)',
        pwa: 'var(--pwa-color)',
        'btn-border': 'var(--primary-btn-border-color)',
        'demo-btn-border': 'var(--demo-btn-border-color)',
        'bet-option': 'var(--bet-option-color)',
        'bet-option-active': 'var(--bet-option-active-color)',
        'bet-option-active-title': 'var(--bet-option-active-title-color)',
        'bet-float': 'var(--bet-float-color)',
        amount: 'var(--amount-color)',
        'second-input-hover-bd': 'var(--second-hover-input-border)',
        'bet-option-text': 'var(--bet-option-text-color)',
        pagination: 'var(--pagination-color)',
        'pagination-active': 'var(--pagination-active-color)',
        'pagination-hover': 'var(--pagination-hover-color)',
        'rebate-btn-tx': 'var(--rebate-btn-color)',
        'rebate-tip-tx': 'var(--rebate-tip-color)',
        'info-border': 'var(--info-border-color)',
        'header-tx': 'var(--header-color)',
        'amount-btn-border': 'var(--amount-btn-border-color)',
        'rebate-border': 'var(--rebate-border-color)',
        'rebate-bold-border': 'var(--rebate-bold-border-color)',
        'sidebar-hover': 'var(--sidebar-hover-color)',
        'sidebar-active': 'var(--sidebar-active-color)',
        'sidebar-tx-color': 'var(--sidebar-tx-color)',
        'profile-info-border': 'var(--profile-info-border-color)',
        'vip-ring': 'var(--vip-ring-color)',
        'login-member-hover': 'var(--login-member-hover)',
        'no-data-btn-active': 'var(--no-data-btn-active-color)',
        'download-mouse': 'var(--download-mouse-color)',
        'white-game-btn-tx': 'var(--white-game-btn-color)',
        version: 'var(--version-color)',
        about: 'var(--about-color)',
        'about-info-tx': 'var(--about-info-color)',
        'pc-about-info-tx': 'var(--pc-about-info-color)',
        'step-border': 'var(--step-border)',
        'step-active-border': 'var(--step-active-border)',
        'step-active': 'var(--step-active-color)',
        'wallet-index-tx': 'var(--wallet-index-color)',
        'detail-index-tx': 'var(--detail-index-color)',
        'exchange-btn-tx': 'var(--exchange-btn-color)',
        'exchange-active-tx': 'var(--exchange-active-color)',
        'exchange-active-border': 'var(--exchange-active-border-color)',
        'download-active-tx': 'var(--download-active-color)', // merge完確認沒問題可刪除, 改為active-color
        'country-border': 'var(--country-border-color)',
        'sms-disable-btn-tx': 'var(--sms-disable-btn-color)',
        'platform-switch': 'var(--platform-switch-border)',
        'primary-sidebar-btn': 'var(--primary-sidebar-btn-color)',
        'sport-b-select-sport-font': 'var(--sport-b-select-sport-font-color)',
        'header-btn-bg': 'var(--header-btn-bg)',
        'header-btn-tx': 'var(--header-btn-tx)',
        'header-btn-tx-shadow': 'var(--header-btn-tx-shadow)',
        'header-btn-border': 'var(--header-btn-border)',
        'header-btn-box-shadow': 'var(--header-btn-box-shadow)',
        'lottery-info-bg': 'var(--lottery-info-bg)',
        'lottery-table-border': 'var(--lottery-table-border)',
        'lottery-table-head-bg': 'var(--lottery-table-head-bg)',
        'tag-active': 'var(--tag-active-color)',
        reset: 'var(--reset-color)',
        highlight: 'var(--highlight-color)',
        'sport-type-tx': 'var(--sport-type-tx-color)',
        'footer-tx': 'var(--footer-tx-color)',
        'footer-tx-active': 'var(--footer-tx-active-color)',
        'footer-icon': 'var(--footer-icon-color)',
        'footer-icon-active': 'var(--footer-icon-active-color)',
        'online-service-icon': 'var(--online-service-icon-first-color)',
        'date-active': 'var(--date-active)',
        'active-progress': 'var(--active-progressive)',
        'mobile-e-category-tx': 'var(--mobile-e-category-btn-tx)',
        'mobile-e-category-tx-active': 'var(--mobile-e-category-btn-active-tx)',
      },
      borderRadius: {
        btn: 'var(--btn-border-radius)',
        normal: 'var(--normal-border-radius)',
        modal: 'var(--modal-radius)',
        'online-btn': 'var(--online-service-rounded)',
      },
      fontSize: {
        'pc-sz': 'var(--pc-font-size)',
        'mobile-sz': ['var(--mobile-font-size)', '1.375rem'],
        'modal-title': 'var(--modal-title-font-size)',
        'mobile-title': 'var(--mobile-title-font-size)',
        'pc-title': 'var(--pc-title-font-size)',
      },
      spacing: {
        'pc-header': 'var(--pc-header-height)',
        'pc-header-b': '136px',
        'pc-header-has-download-hint': 'var(--pc-header-height-has-download-hint)',
        'mobile-header': 'var(--mobile-header-height)',
        'mobile-header-has-download-hint': 'var(--mobile-header-height-has-download-hint)',
        'pc-header-gap': 'var(--pc-header-gap)',
        'tablet-header-gap': 'var(--tablet-header-gap)',
        'mobile-header-gap': 'var(--mobile-header-gap)',
        '1/2-m-2.5': 'calc(50% - 5px)',
        '1/3-m-2.5': 'calc(33.33% - 7px)',
        '1/3-m-5': 'calc(33.33% - 14px)',
        '1/4-m-2.5': 'calc(25% - 8px)',
        '1/5-m-2.5': 'calc(20% - 8px)',
        'quick-input-btn-pc': 'calc(20% - 8px)',
        'quick-input-btn-mobile': 'calc(25% - 8px)',
        'pc-selection-wallet': 'calc(50% - 20px)',
        'pc-header-close': 'calc(100% - 84px)',
        'pc-header-open': 'calc(100% - 300px)',
        '1/7': 'calc(14.2857%)',
        'logo-left': 'var(--logo-left)',
      },
      boxShadow: {
        header: 'var(--header-shadow)',
        dropdown: 'var(--dropdown-shadow)',
        'sidebar-top': 'var(--sidebar-top-shadow)',
        'mobile-game-category': 'var(--mobile-game-category-shadow)',
        'bet-profit': 'var(--bet-profit-shadow)',
        'header-dropdown': 'var(--header-dropdown-shadow)',
        download: 'var(--download-shadow)',
        sidebar: 'var(--sidebar-shadow)',
        'vip-info': 'var(--vip-info-shadow)',
        'primary-btn': 'var(--primary-btn-shadow)',
      },
      opacity: {
        'game-bg': 'var(--game-bg-opacity)',
      },
      screens: {
        sm: '560px',
        '2md': '990px',
        '3md': '1025px', // ipad Pro
        xl: '1200px', // pc
        '2xl': '1440px',
        '3xl': '1500px',
        '4xl': '1600px',
      },
      transitionDuration: {
        base: '300ms',
      },
      keyframes: {
        'slide-left': {
          from: { transform: 'translate(0)' },
          to: { transform: 'translate(-100%)' },
        },
        'slide-left-in': {
          from: { transform: 'translate(-100%)' },
          to: { transform: 'translate(0)' },
        },
        'fade-in': {
          from: {
            opacity: 0,
          },
          to: {
            opacity: 100,
          },
        },
        'fade-out': {
          from: {
            opacity: 100,
          },
          to: {
            opacity: 0,
          },
        },
        rotate: {
          from: {
            transform: 'rotate(360deg)',
          },
          to: {
            transform: 'rotate(0deg)',
          },
        },
        'rotate-back': {
          from: {
            transform: 'rotate(-360deg)',
          },
          to: {
            transform: 'rotate(0deg)',
          },
        },
      },
      animation: {
        'slide-left-450': 'slide-left 4.5s linear forwards',
        'fade-in-300': 'fade-in 0.3s ease-in-out forwards',
        'fade-in-800': 'fade-in 0.8s ease-in-out forwards',
        'fade-out-300': 'fade-out 0.3s ease-in-out forwards',
        'fade-out-800': 'fade-out 2s ease-in-out forwards',
        rotate: 'rotate 0.5s linear infinite forwards',
        'rotate-back': 'rotate-back 0.5s linear infinite forwards',
      },
      zIndex: {
        header: 10,
        'download-hint': 13,
        footer: 9,
        tab: 9,
        'float-item': 11,
        'pc-sidebar': 11,
        'mobile-sidebar': 12,
        'tablet-sidebar-mask': 8,
        search: 20,
        redirect: 30,
        game: 9999,
        'game-option': 10000,
      },
      width: {
        platform: 'calc(50% - 10px)',
        'game-item-xl': 'calc(16% - 10px)',
        'game-item-md': 'calc(19% - 10px)',
        unset: 'unset',
      },
      // fontFamily: {
      //   anton: 'Anton, sans-serif',
      // },
      fill: {
        icon: 'var(--icon-color)',
        'invite-reward-trophy': 'var(--share-reward-trophy)',
        'invite-reward-none-trophy': 'var(--share-reward-none-trophy)',
        sidebar: 'var(--icon-color-sidebar)',
        'sidebar-hover': 'var(--icon-color-sidebar-hover)',
        'sidebar-active': 'var(--icon-color-sidebar-active)',
        'sidebar-toggle': 'var(--icon-color-sidebar-toggle)',
        header: 'var(--icon-color-header)',
        'mobile-header': 'var(--icon-color-mobile-header)',
        'header-active': 'var(--icon-color-header-active)',
        'header-dropdown': 'var(--icon-color-header-dropdown)',
        sport: 'var(--icon-color-home-sport)',
      },
    },
  },
};
